# Talkatone 广告重写（配合 filter 使用）
# raw: https://raw.githubusercontent.com/carlleilzj/Talkatone_Rules/main/QuantumultX/Talkatone_Ads_Rewrite.conf

[rewrite_local]
^https?:\/\/lb-iad-[^.]+\.tktn\.be\/ url reject-dict
^https?:\/\/.*\.tk0x1\.com\/ url reject-dict
^https?:\/\/.*\.smadex\.com\/ url reject-img
^https?:\/\/.*\.jampp\.com\/ url reject-img
^https?:\/\/cdn\.mobilefuse\.com\/ url reject-img
^https?:\/\/cdn2\.inner-active\.mobi\/ url reject-img
^https?:\/\/cdn-f\.adsmoloco\.com\/ url reject-img
^https?:\/\/cdn\.liftoff-creatives\.io\/ url reject-img
^https?:\/\/mfx\.mobilefuse\.com\/ url reject-dict
^https?:\/\/ads\.inmobi\.com\/ url reject-dict
^https?:\/\/config\.inmobi\.com\/ url reject-dict
^https?:\/\/.*\.smaato\.net\/ url reject-dict
^https?:\/\/googleads\.g\.doubleclick\.net\/ url reject-dict
^https?:\/\/alt-r\.my\.com\/mobile url reject-dict
^https?:\/\/imgx\.jampp\.com\/ url reject-img

[mitm]
hostname = lb-iad-*.tktn.be, *.tk0x1.com, *.smadex.com, *.jampp.com, cdn.mobilefuse.com, mfx.mobilefuse.com, cdn2.inner-active.mobi, *.inner-active.mobi, cdn-f.adsmoloco.com, cdn.liftoff-creatives.io, ads.inmobi.com, config.inmobi.com, *.smaato.net, googleads.g.doubleclick.net, alt-r.my.com, imgx.jampp.com
